"""initial_schema

Revision ID: 684a9adcc09d
Revises: 
Create Date: 2026-03-30 12:27:12.411875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '684a9adcc09d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=False),
    sa.Column('income_level', sa.String(length=100), nullable=False),
    sa.Column('psychographic_notes', sa.Text(), nullable=True),
    sa.Column('persona_count', sa.Integer(), nullable=False),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_group_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=False),
    sa.Column('income_level', sa.String(length=100), nullable=False),
    sa.Column('educational_background', sa.Text(), nullable=True),
    sa.Column('family_situation', sa.Text(), nullable=True),
    sa.Column('personality_traits', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('values_and_motivations', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('media_consumption', sa.Text(), nullable=True),
    sa.Column('purchase_behavior', sa.Text(), nullable=True),
    sa.Column('raw_profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_group_id'], ['persona_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('persona_group_id', sa.UUID(), nullable=False),
    sa.Column('briefing_id', sa.UUID(), nullable=False),
    sa.Column('prompt_question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ),
    sa.ForeignKeyConstraint(['persona_group_id'], ['persona_groups.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('reaction_text', sa.Text(), nullable=True),
    sa.Column('key_themes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notable_quote', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('sentiment_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_themes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_results')
    op.drop_table('simulations')
    op.drop_table('personas')
    op.drop_table('persona_groups')
    op.drop_table('briefings')
    op.drop_table('projects')
    # ### end Alembic commands ###
